### PR TITLE
Add Clang builds

### PR DESCRIPTION
**Pull request by xgdgsc**
Please see https://app.travis-ci.com/github/xgdgsc/csv-parser/builds/233738949 for various build errors on gcc/clang. Why isn' t travis working at your master branch?

### CODE REVIEW

**Comment by vincentlaucsb** [comment]
I have no idea. When travis-ci moved from .org to .com I had to recreate my account and for some reason all of my repos with a .travis.yml aren't recognized.

The build errors are due to another PR that brought in some very restrictive error flags when `IF (UNIX)` is true. I might remove a few, while fixing a few others. If you remove the flags however, the library should build.

**Comment by xgdgsc** [comment]
You might need to enable repo at https://app.travis-ci.com/dashboard

**Comment by xgdgsc** [comment]
Or at settings https://app.travis-ci.com/account/repositories ,  click " Manage repositories on GitHub"

**Comment by vincentlaucsb** [comment]
That's the problem. It shows all of my repos except for the ones that I actually used with Travis in the past.

**Comment by xgdgsc** [comment]
https://travis-ci.com/github/vincentlaucsb/csv-parser what if you access this url?

**Comment by vincentlaucsb** [comment]
image
🤷

**Comment by vincentlaucsb** [comment]
This is a good PR and something I've wanted to do for a while. I created a ticket with the Travis CI team and hopefully they can fix this.

**Comment by vincentlaucsb** [comment]
I've just migrated my repos over from travis-ci.org to travis-ci.com. Let's see what happens.

**Pull request merged**
