### PR TITLE
Adding python bindings for the library.

### PR DESCRIPTION
**Pull request by Ho011**

### CODE REVIEW

**Comment by vincentlaucsb** [comment]
Could you make Python building off by default? I don't think most users will use them.

But otherwise, this looks pretty awesome. I've always wanted to create Python bindings, but never got the chance. I'll review it ASAP.

**Comment by Ho011** [comment]
> Could you make Python building off by default? I don't think most users will use them.
> 
> But otherwise, this looks pretty awesome. I've always wanted to create Python bindings, but never got the chance. I'll review it ASAP.

Yes you're right a few people may use it, becaus python already provided a standard csv reader  but people who want to speed up their python code will use it, it's much faster than python standard csv reader.

**Comment by vincentlaucsb** [comment]
> > Could you make Python building off by default? I don't think most users will use them.
> > But otherwise, this looks pretty awesome. I've always wanted to create Python bindings, but never got the chance. I'll review it ASAP.
> 
> Yes you're right a few people may use it, becaus python already provided a standard csv reader but people who want to speed up their python code will use it, it's much faster than python standard csv reader.

What I mean is that a lot of people only use this in a C++-only environment. I'd like to keep the default options minimal and allow people to turn on additional features as they'd like.

**Comment by Ho011** [comment]
> > > Could you make Python building off by default? I don't think most users will use them.
> > > But otherwise, this looks pretty awesome. I've always wanted to create Python bindings, but never got the chance. I'll review it ASAP.
> > 
> > 
> > Yes you're right a few people may use it, becaus python already provided a standard csv reader but people who want to speed up their python code will use it, it's much faster than python standard csv reader.
> 
> What I mean is that a lot of people only use this in a C++-only environment. I'd like to keep the default options minimal and allow people to turn on additional features as they'd like.

OK, I get it now

**Pull request merged**
