### PR TITLE
CMake: Fix Python3 and Doxygen invocations.

### PR DESCRIPTION
**Pull request by tamaskenez**

### CODE REVIEW

**Comment by tamaskenez** [comment]
There are a few things I need to say:

- Sorry about the many changes, I did not want to include all of these changes in to the 2 PRs. I just pushed new commits to my master and forgot that they will show up in the PR. So let's put this on hold, tomorrow I'll remove the unwanted changes and you can review again.
- In CMake the general rule is to not check `CMAKE_BUILD_TYPE` ever, because it's meaningless with IDE-generators (like MSVC, Xcode).
- You can still set config dependent flags with `CMAKE_CXX_FLAGS_DEBUG`, etc... but CMake already adds all the necessary `-O` flags to DEBUG and non-DEBUG builds.
- I probably made one error here: I removed `-pthread` but the parser does need `pthread` with gcc, right? Even if it does, there's a better way to add it, I'll do it tomorrow.

**Comment by vincentlaucsb** [comment]
Yes the CSV parser uses threads and won't compile without -pthread

**Comment by tamaskenez** [comment]
I removed the unnecessary changes from my master, so this is only 1 file, please review.

**Comment by vincentlaucsb** [comment]
Do you think it's possible to incorporate the suggestions from #6?

**Comment by tamaskenez** [comment]
> Do you think it's possible to incorporate the suggestions from #6?

Yes, I can do it. I mean, I suggest not to extend to scope of this PR. I'll do it in a separate CL.

**Comment by vincentlaucsb** [comment]
Yes you're right. Thanks again for your help!

**Pull request merged**
